name: Deploy to GCR

on:
  push:
    branches:
      - main

jobs:
  build-and-push-to-gcr:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - uses: actions/checkout@v3
      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          service_account: hacknosis-server-gar-sa@hacknosis.iam.gserviceaccount.com
      - uses: RafikFarhad/push-to-gcr-github-action@v5-rc1
        with:
          gcloud_service_key: ${{ secrets.GCLOUD_GCR_AUTH_KEY }} # can be base64 encoded or plain text || not needed if you use google-github-actions/auth
          registry: pkg.dev
          project_id: hacknosis
          image_name: backend
          image_tag: latest,v1
          dockerfile: Dockerfile
          context: ../../